### PR TITLE
Source regressor

### PR DESCRIPTION
**Pull request by MaxNoe**
Train and apply regressor for disp and a classifier for the sign of delta.

The improvements over FACT-Tools standard analysis should be quite big, especially in high energy. More to come here.

### CODE REVIEW

**Comment by MaxNoe** [comment]
First results here:

Compared with the ICRC analysis, I now reach 51.3 σ as compared to 43.3 σ. Noteworthy is that this is the result of a 20 % reduction in excess events and n_off nearly cut in half.

### New  θ² plot
theta2_plot

### ICRC version

theta2_plot_icrc

**Comment by MaxNoe** [comment]
The lower energies unfortunately got a bit worse:
### new version
angular_resolution

### ICRC version
angular_resolution_icrc

**Comment by MaxNoe** [comment]
And here is now the skymap, produced together with the PR in pyfact:
https://github.com/fact-project/pyfact/pull/72

https://user-images.githubusercontent.com/5488440/30747278-03d5c242-9fad-11e7-8bdf-21765e7edbdf.png

**Comment by MaxNoe** [comment]
I think this is ready for merge now. Please review!

**Comment by jebuss** [comment]
I have nothing to complain. Please merge whenever you like

**Pull request merged**
